### ISSUE TITLE
Add to cart not firing for grouped products list

### ISSUE THREAD

**Issue by lucspe** [duracelltomi/gtm4wp#256] opened 2023-03-06 12:00 UTC
Hi, I am having trouble with grouped products list (so a page which shows like the sample GTM4WP dev site: https://woo.gtm4wp.dev/product/grouped-sample-product).

When add to cart is clicked, I would expect that an add_to_cart event is fired and the contents of the list are passed (this is what happens when using other similar plugins). However in GTM4WP it doesn't seem to work.

To make sure, I even tried changing default theme to StoreFront and removing other plugins other than WooCommerce and GTM4WP.

Any suggestions on how I could further investigage the issue?

**Comment by duracelltomi** [comment] 2023-03-07 08:18
Hi,

Perhaps I just did not understand the question correctly, but this is what I see happening on the mentioned dev site:

![image](https://user-images.githubusercontent.com/7515949/223363930-a43e3293-947a-452e-a78d-0ad8608e9ef3.png)

Or this is only not working on your site?

**Comment by lucspe** [comment] 2023-03-07 09:09
Hi Tamas,

Thanks for replying.

Indeed i linked the page on dev site only as a reference, apologies for the misunderstanding.

The issue appears on my site. It records only view item and view item list when the form is submitted.

I tried with different GTM plugins and it works as expected so i am a bit lost on what to do next to try and find what is that is missing for GTM4WP (which is what i would prefer to use as it is by far the most comprehensive plugin for this) to fire the event.

**Comment by duracelltomi** [comment] 2023-04-03 13:43
I've found the bug: when you select to use SKU instead of the internal product ID, this feature was broken.
This should fix it: https://github.com/duracelltomi/gtm4wp/commit/5ecb4c13e510a4427a081130da76bca14eff1f6b

**Comment by FloydHD** [comment] 2023-05-30 22:57
Hi.

I've got a similar problem.
The gtm4wp.addProductToCartEEC event fires correctly when adding a single product to the cart, but nothing happens when I try to add products from a grouped product to the cart.
I also have no luck getting the begin checkout event to fire, but that's another topic :/

single product -> https://fmp-equipment.de/produkt/001_010/
grouped product -> https://fmp-equipment.de/produkt/001/

What I've already done:
    - compared HTML structure to GTM4WP testing site -> https://woo.gtm4wp.dev/product/grouped-sample-product
    	=> only difference I could find was the different quantity selectors. I already tested with the standard quantity selectors, so the HTML structure is completely the same 
    - compared HTML structure to original WooCommerce grouped.php file
        => identical, with small edits from my side. I already tested it with the standard grouped.php
    - checked the usage of all needed WooCommerce actions and filters, as well as class names as stated here -> https://gtm4wp.com/gtm4wp-for-developers/how-to-make-your-wordpress-theme-compatible-with-enhanced-ecommerce-tracking
    	=> all seem so be in place
    	=> Tip: maybe add the file locations where the actions and filters are expended to be used.


I hope you can help me here, because I was trying for a few hours already, hoping to get this to work. Apart from these problems I really like the plugin and documentation so faar!

**Comment by Floyd-Schramm** [comment] 2023-06-02 17:10
@duracelltomi @lucspe any updates on the topic?

**Comment by duracelltomi** [comment] 2023-06-13 15:13
@Floyd-Schramm do you have a testing version of the site where site caching and optimizations can be turned off?

From what i can see the problem is related to what has been fixed in 1.17:
https://github.com/duracelltomi/gtm4wp/releases

Finally I will have time tomorrow to release it on WP.org AND follow first reactions.

**Comment by Floyd-Schramm** [comment] 2023-06-17 20:18
@duracelltomi I currently have no site without caching/optimizations but I could try to set one up for testing.

I have not gotten an update for the GTM4WP plugin through WP so I manually installed the new version and now the add-to-cart event fires but with incorrect quantity data.

These are the products I added to the cart:
![image](https://github.com/duracelltomi/gtm4wp/assets/29488767/10b2bf6a-a481-492f-9f0d-b49c757c6056)

And this is the data GTM got from the plugin:
![image](https://github.com/duracelltomi/gtm4wp/assets/29488767/1036eca3-3b03-4032-a05d-20b38c6f40ab)

As you can see, GTM got the info that I added all available product versions to the cart, which is incorrect (I only added 2 and not all 6 versions). Do you have any idea how to fix this?

**Closed** 2023-08-28 13:53 UTC
Labels: needs testing

**Comment by Floyd-Schramm** [comment] 2023-08-28 13:58
@duracelltomi this issue is still not resolved!

**Comment by duracelltomi** [comment] 2023-08-28 14:39
Sorry, I was cleaning up and accidentally closed this ticket.

**Comment by brthmrk** [comment] 2024-08-07 11:37
Any solutions yet?

**Comment by duracelltomi** [comment] 2024-08-16 13:50
The code samples earlier were from version v1.17 and related to the old version of the ecommerce data layer that has been already removed. Are you sure you still experience the issue? Can you reproduce the issue on https://woo.gtm4wp.dev/?

**Comment by brthmrk** [comment] 2024-08-20 09:28
Still got the issue on:
https://www.rentyourmac.com/cloud/product/additional-software-final-cut-pro-x/
And: https://www.rentyourmac.com/cloud/product/mac-mini-m2-2023/


Met vriendelijke groet,

[image: brthmrk werknemer]
Jim Servaas
Eigenaar
[image: phone icon] 0683234700
[image: email icon] ***@***.***
[image: location icon] Affuitenhal 1 (Unit 1.03), Zaandam
[image: site icon] www.brthmrk.nl

[image: brthmrk logo]


Op vr 16 aug 2024 om 15:51 schreef Thomas Geiger ***@***.***>:

**Comment by duracelltomi** [comment] 2026-07-14 13:45
Sorry for the delay in the response, a fully reworked 2.0 plugin version is being built that has this issue resolved. Stay tuned for the first beta released soon.
