### ISSUE TITLE
AMP module adding a string above the header

### ISSUE THREAD

**Issue by dascalescuro** [duracelltomi/gtm4wp#120] opened 2019-05-17 02:31 UTC
Great work with the plugin! I want to report a situation:

Using Neve WordPress theme, AMP official plugin (https://wordpress.org/plugins/amp/) and your plugin for GTM implementation. [site link](https://www.dascalescu.ro/?amp)

On mobile, the plugin adds a string above the header: https://i.imgur.com/msGTnsB.png I this something @koconder can take a look at?

Thanks

CC: @duracelltomi

**Comment by dascalescuro** [comment] 2019-05-25 08:35
@duracelltomi @koconder this needs a fix and should be labeled as bug

**Comment by dascalescuro** [comment] 2019-06-01 17:16
@duracelltomi the reason you sent me to open an issue and ping @koconder is to ignore the fact that a plugin in the official WP directory is ignoring a bug?

**Comment by duracelltomi** [comment] 2019-06-02 06:18
This is not the case for sure. I am not ignoring bugs, but this part of the plugin was not developed by me.

Since you did not receive any response here, I will start investigating this tomorrow.

I will update this thread on Monday evening (CET time) with any further questions or updates

**Comment by duracelltomi** [comment] 2019-06-02 06:23
I forgot to mention my apologies for the delay in this thread :-(

**Comment by dascalescuro** [comment] 2019-06-03 12:56
Thanks @duracelltomi I understand it was not developed by you.

When contributors are helping with the plugin maybe it will be good to have an option to disable a particular feature.

In this case, I am not using the AMP feature in GTM4WP and the string shows in each page and there is nothing I can do.

I had to deactivate the AMP plugin which is not ideal.

Thanks again and I am sorry for pushing this but seems to be a big problem with an easy fix (at least I hope so)

**Comment by koconder** [comment] 2019-06-04 00:58
@dascalescuro if you can confirm if the issue is resolved or not after changing theme I can provide support/bug-fix accordingly.

**Comment by dascalescuro** [comment] 2019-06-06 12:53
@koconder @duracelltomi it seems that the problem is mixed.

because I was using the Codeless Injection method to add the GTM script and because of AMP the string was displayed on the frontend.

Now I changed it to Footer to add GTM script and the string is gone.

Maybe try the [new wp_body_open()](https://developer.wordpress.org/reference/functions/wp_body_open/) function instead of using the Codeless Injection but on my end, I consider this solved.

Thanks for taking the time to look into it.

**Comment by koconder** [comment] 2019-06-10 10:18
This relates to #116 we will possibly look at defaulting AMP to footer in Codeless mode unless its custom or wp_body_open

**Comment by duracelltomi** [comment] 2019-06-19 15:39
Thanks @koconder for the ongoing help!

**Comment by koconder** [comment] 2019-06-20 01:48
@duracelltomi & @dascalescuro i have made some improvements to AMP.

We are now able to use a mix of amp_wp_body_open() and amp_post_template_footer() for fallback

Waiting on PR for amp_post_template_body_open() to be approved here https://github.com/ampproject/amp-wp/pull/1143 - If you can add your support there for an AMP equivalent of amp_post_template_body_open()

**Comment by dascalescuro** [comment] 2019-06-20 08:02
thanks for looking into this 🥂

**Comment by danipolo** [comment] 2019-06-27 23:01
Thank you so much @koconder !

**Comment by koconder** [comment] 2019-06-28 00:43
@dascalescuro and @danipolo your welcomed to comment on https://github.com/ampproject/amp-wp/pull/1143 asking for it to be added in :)

**Comment by koconder** [comment] 2019-06-30 08:59
@duracelltomi #125 is now active as the PR on ampproject has now been merged pending release.

**Comment by duracelltomi** [comment] 2019-07-10 06:23
Thanks!

Since #125 was already merged, am I right that nothing more is needed on this side to make this work?

**Comment by koconder** [comment] 2019-07-28 05:24
@duracelltomi we can safely close this issue.

**Closed** 2019-07-29 14:45 UTC
