### ISSUE TITLE
Add option to configure GTM-id via wp-config

### ISSUE THREAD

**Issue by mikaelengstrom** [duracelltomi/gtm4wp#133] opened 2019-08-06 08:28 UTC
It would be great to have the option to configure the GTM-id via settings files for those who want to be able to sync databases between environments and have different GTM-id´s for stage and production. Right now i manually have to update the setting after every sync or write some database migration script. It would be much nicer to be able to implement such credentials via .env-files in a [Twelv-Factor App fashion](https://12factor.net/config).

The way i see the feature, if you set `define("GTM4WP_GTM_ID", "GTM-MYID")` in wp-config the field gets grayed out in wp-admin and an informational text informs the user something like: "This setting is controlled from code in wp-config.php". If the GTM4WP_GTM_ID constant is not set at all, it works like it does now, which is great for most use-cases.

**Comment by duracelltomi** [comment] 2019-08-07 07:29
To add more into this: since GTM has [environments](https://support.google.com/tagmanager/answer/6311518?hl=en) too, I would add the necessary GTM environment variables into wp-config too so that the proper environment ID can be selected on specific instances of your site

What do you think of this?

**Comment by mikaelengstrom** [comment] 2019-08-07 08:39
Thanks for picking this up, I think environments sounds great! I it were up to me I would love to have all settings in code since it allows for version control of settings. However that is probably not requested enough to justify the increased cost in maintenance :)

**Comment by duracelltomi** [comment] 2019-08-07 13:14
Well, I am open to any reasonable change :-)

I wonder how other plugins deal with this situation? GTM4WP uses the same approach as most other plugins: using the WP Settings API to store plugin settings in DB. But from what I can understand in your initial message, this might be not the best way if there are multiple environments of the same site.

wp-config was not meant to store complete sets of plugin and theme options, I sure about that.

What could be the in-between solution that also fits into how WP was designed and coded?

**Comment by mikaelengstrom** [comment] 2019-08-07 20:56
Glad to hear that :) 

Here ar my thoughts on your questions regarding whatever is the "right way" and what others do: I believe the WP-community is split into two camps. On one hand you have this huge community which run WP on cheap shared hosting, install some plugins and a theme via the admin interface and they have a decent site up and running in a few hours. In my opinion this is really the true strength in WP, and to be able to do that you need to be able to configure everything via the admin interface. Hence, a plugin like GTM4WP should for sure prioritise these users.  On the other hand you have huge sites handling tons of traffic running on complex infrastructures. These setups require ways to separate environment-specific configuration (e.g. GTM-code, hostnames to services, etc.) and are much easier to maintain and debug if as much settings as possible is under version control. It also makes automated integration tests a lot easier. Plugins which are mostly targeting these users sometimes put all settings in constants or code in some way and do not even provide admin interface for configuration (e.g. [Wp redis cache](https://wordpress.org/plugins/redis-cache/), [soil](https://github.com/roots/soil)).  

Another example is ACF which gives you the possibility to dump all configuration to json-files every time they change in wp-admin, the JSON-files are then used by the production-servers. So you configure it via admin on your local environment, check in the JSON-files, push to prod and bam; your change is live and under version control ([ACF local-json feature](https://www.advancedcustomfields.com/resources/local-json/)).

I do not know what is right for GTM4WP, since it is not only targeting developers but also people who work only/mostly with analysis as well as the shared hosting users I think handling of all settings in version-control might be overkill, even though I personally would love it.  Regarding my original proposal with just the environment specific settings to ease data syncronizations between environments I think that ElasticPress is a great example.  You could configure via wp-admin, or you could set the [EP_HOST-constant](https://github.com/10up/ElasticPress/blob/b3d96a72dd54db1def357d6c0f093a2a182b6e06/includes/utils.php#L157-L163). If the constant is set, that take priority over whatever setting is use. if you go to the admin-page the field for that option is grayed out, disabled and have an informative text that explains why you can not change it from wp-admin. I beleive that this is the "In between solution".

**Comment by jlauding** [comment] 2019-08-28 10:59
👍

**Comment by duracelltomi** [comment] 2019-08-30 06:09
I've just added the necessary code changes as you can see in the reference above.
Before I close this ticket, I would like to discuss on more important topic regarding this change: security

I wonder whether this could be used by attackers to replace the container running in the site to another which includes codes harmful JS codes?
I also wonder if there is any need to validate the value of the newly introduced PHP constants before using them to output the GTM container code?

Some of my thoughts:
* perhaps I should check at least that the entered container ID is valid but this check will run on every page view which could be a performance issue
* or I should say that anyone using this feature should be careful enough to enter valid data in the constants?
* Google has a malware scanner which would disable a GTM container if a known bad JS code is added thus an attacker can only prepare a GTM container which includes very unique malicious code
* But an attacker could also change the value of the db option which would load another GTM container anyway so perhaps this addition is not introducing any easier/new way to use the plugin as an attack vector?

**Comment by mikaelengstrom** [comment] 2019-08-30 14:14
Hi, great job with the commit. 

Regarding security, I do not really see an attack surface here. The only way to sneak in a malicious GTM-id in a PHP constant would be if the attacker had the possibility to manipulate the PHP-files in some way. If the attacker have that kind of access they could do far worse than injecting js via GTM and could probably inject it directly via <script> tags. In fact, the DB setting is far more attackable. Am I missing something or misunderstanding your concerns?

**Comment by duracelltomi** [comment] 2019-08-30 14:37
No, this is what I can see too, I just wanted to validate my thoughts with someone :-)

**Closed by duracelltomi** 2019-08-30 14:37 UTC
Labels: enhancement
